version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: talabalar
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # optional: expose for debugging; you can remove on prod

  api:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/talabalar?schema=public
      JWT_SECRET: ${JWT_SECRET:-dev_secret}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data:
