openapi: 3.1.0
info:
  title: Talabalar Ro'yhati API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/v1/students:
    get:
      summary: List students
      parameters:
        - in: query
          name: page
          schema: { type: integer, default: 1, minimum: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 10, minimum: 1, maximum: 100 }
        - in: query
          name: sort
          schema: { type: string }
        - in: query
          name: faculty
          schema: { type: string }
        - in: query
          name: group
          schema: { type: string }
        - in: query
          name: status
          schema: { type: string, enum: [active, graduated, expelled, academic_leave] }
        - in: query
          name: search
          schema: { type: string }
      responses:
        '200':
          description: OK
    post:
      summary: Create student
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentCreate'
      responses:
        '201':
          description: Created
  /api/v1/students/export.csv:
    get:
      summary: Export students as CSV
      parameters:
        - in: query
          name: sort
          schema: { type: string }
        - in: query
          name: faculty
          schema: { type: string }
        - in: query
          name: group
          schema: { type: string }
        - in: query
          name: status
          schema: { type: string, enum: [active, graduated, expelled, academic_leave] }
        - in: query
          name: search
          schema: { type: string }
      responses:
        '200':
          description: CSV file
          content:
            text/csv:
              schema:
                type: string
                format: binary
  /api/v1/students/import:
    post:
      summary: Import students from CSV
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required: [file]
      responses:
        '201':
          description: Import summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  inserted: { type: integer }
                  invalid: { type: integer }
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        row: { type: integer }
                        message: { type: string }
  /api/v1/students/{id}:
    get:
      summary: Get student by id
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
        '404': { description: Not Found }
    patch:
      summary: Update student
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentUpdate'
      responses:
        '200': { description: OK }
    delete:
      summary: Delete student
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '204': { description: No Content }
  /api/v1/students/{id}/profile-picture:
    post:
      summary: Upload profile picture
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                picture:
                  type: string
                  format: binary
              required: [picture]
      responses:
        '200':
          description: Profile picture uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  profile_picture: { type: string }
    delete:
      summary: Delete profile picture
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Profile picture deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
  /api/v1/auth/login:
    post:
      summary: Login to obtain JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username: { type: string }
                password: { type: string }
      responses:
        '200':
          description: Token issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token: { type: string }
                  token_type: { type: string, example: Bearer }
components:
  schemas:
    Student:
      type: object
      properties:
        id: { type: string }
        full_name: { type: string }
        faculty: { type: string }
        group: { type: string }
        email: { type: string, nullable: true }
        phone: { type: string, nullable: true }
        birth_date: { type: string, format: date-time }
        enrollment_year: { type: integer }
        status: { type: string, enum: [active, graduated, expelled, academic_leave] }
        profile_picture: { type: string, nullable: true }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
    StudentCreate:
      type: object
      required: [full_name, faculty, group, birth_date, enrollment_year]
      properties:
        full_name: { type: string }
        faculty: { type: string }
        group: { type: string }
        email: { type: string }
        phone: { type: string }
        birth_date: { type: string, format: date }
        enrollment_year: { type: integer }
        status: { type: string, enum: [active, graduated, expelled, academic_leave], default: active }
    StudentUpdate:
      type: object
      properties:
        full_name: { type: string }
        faculty: { type: string }
        group: { type: string }
        email: { type: string }
        phone: { type: string }
        birth_date: { type: string, format: date }
        enrollment_year: { type: integer }
        status: { type: string, enum: [active, graduated, expelled, academic_leave] }
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
