name: CI/CD (EC2 Docker Compose)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U postgres; then echo "postgres ready"; exit 0; fi; sleep 2; done; exit 1

      - name: Prepare Prisma client
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb?schema=public
        run: npx prisma generate

      - name: Run DB migrations (test)
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb?schema=public
        run: npx prisma migrate deploy || npx prisma db push

      - name: Test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb?schema=public
          JWT_SECRET: test_secret
          ADMIN_USERNAME: admin
          ADMIN_PASSWORD: admin123
        run: npm test --if-present
        continue-on-error: true

  deploy:
    name: Deploy to EC2
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      REPO_URL: https://github.com/${{ github.repository }}.git
      APP_DIR: ${{ secrets.APP_DIR }}
    steps:
      - name: Connect and deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          script: |
            set -euo pipefail
            if [ ! -d "$APP_DIR/.git" ]; then
              mkdir -p "$APP_DIR"
              git clone "$REPO_URL" "$APP_DIR"
            fi
            cd "$APP_DIR"
            git fetch --all --prune
            git reset --hard origin/main

            # Optional: set env vars here, or use .env file
            # export JWT_SECRET=${JWT_SECRET}

            docker compose down || true
            docker compose pull || true
            docker compose build --no-cache
            docker compose up -d
            docker compose ps

            echo "Deployed commit: $(git rev-parse --short HEAD)"
